name: cocoapods

on:
  release:
    types: [ published ]
jobs:
  set-user-agent:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push WalletConnectSwiftV2.podspec --verbose --allow-warnings